### ISSUE TITLE
Hard to obtain data from Zenodo

### ISSUE THREAD

**Issue by Fhrozen** [danielkrause/DCASE2022-data-generator#1]
Downloads from Zenodo are getting a time-out, so obtaining the RIR database has become difficult.
https://zenodo.org/record/6408611
It would be helpful if you could upload the database to a different service.

**Comment by polarch** [comment]
Hi,

do you still experience these problems? We also had problems with Zenodo occasionally, but they typically are temporary and get better next day or so. We don't have a better alternative at the moment, but we are considering some possibilities.

**Comment by Fhrozen** [comment]
I just download part of it (z01). I think. I did not try again. I will try once more later.
