### ISSUE TITLE
Trying to use DCASE2022-data-generator, getting randomized Errors

### ISSUE THREAD

**Issue by sadPororo** [danielkrause/DCASE2022-data-generator#2]
I have made through constructing "db_config" class object with my own file paths, but the MetadataSynthesizer keep raising the errors within synthesized senarios.

Can I get some help here?

The majority of the metadata generation failure raisen from..

1.     [metadata_synthesizer.py, line 451]: eventtimetracks[ev_idx, nev] = activity_mask
        In this case, 
            eventtimetracks[ev_idx, nev] has a shape of 1-dimensional array
            activity_mask has shape of (0,) 
        causing broadcast shape mismatch.

2.     [metadata_synthesizer.py, line 494]: stats['polyphony'][nb_active] += 1
        In this case,
            stats['polyphony'] first initialized as np.zeros(self._mixture_setup['nOverlap']+1)
        however,
            nb_active sometimes get the value of self._mixture_setup['nOverlap']+1 that causes Out of Index Error

3.     [metadata_synthesizer.py, line 218]: picked_gaps = np.argwhere(gaps > 2.*mult_min_gap_len)

4.     [metadata_synthesizer.py, line 294]: end_idx = event_span_nl + self._rnd_generator.integers(0, nRirs-event_span_nl+1)
        In this case,
            nRirs-event_span_nl+1 gets negative value,
        so that raising low >= high error from self._rnd_generator.integers(0, nRirs-event_span_nl+1)

**Comment by danielkrause** [comment]
Could you share the content of your generation parameters and DBConfig class? This way we could investigate the case in more detail.

Did you also check if all the required libraries are in their right versions?

**Comment by sadPororo** [comment]
Thanks for your quick response, can I send my parameter.py and db_config class object via your email?

And yes, I checked my library versions, and installed them in the right versions as in "Prerequisites", but "SoundFile"

** The exact version of SoundFile 0.10.3 wasn't availabe, so I installed SoundFile 0.10.3.post1 version.

**Comment by sadPororo** [comment]
Hello Mr. Krause,

Glad to have your considerable response to my issue.


Here's my generation_parameters.py, db_config.py, and db_config object.

** I modified db_config.py-> _make_selected_filelist() function to fit my
audio_path configuration.
** and also some modifications applied on generation_parameter.py for
generation trials.


Again, thank you for your help.

Sincerely, Jin Sob Kim.



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
22.
04. 29. 오후 08:02:06

2022년 4월 29일 (금) 오후 4:20, danielkrause ***@***.***>님이 작성:

**Comment by danielkrause** [comment]
I've went through the case that you sent me and there was indeed a mistake with handling some rare cases with the last indices of some files. It should be fixed now. You can download the updated code and let me know if it works for you. At least the first two errors should disappear. Not sure about no. 3 though - what's the error there?

**Comment by sadPororo** [comment]
For the case of no. 3, I remember that "picked_gaps" sometimes gets an empty array value. 
** But I'm not quite sure of this issue because the case occurs very rarely. 

In the meantime, there are some minor file/folder path configuration issues that should be modified to make the pipeline correctly works with the given RIR and Noise data.

However, I confirmed that both your updated code and the previous version operate well with the minor modifications of try and except.

I appreciate you for taking a look into the issues.
