### ISSUE TITLE
Using the project with FSD50K

### ISSUE THREAD

**Issue by sreenivasaupadhyaya** [danielkrause/DCASE2022-data-generator#6]
Do we need to preprocess the FSD50K dataset before using with this project?
Looks like the project expects the wav files of FSD to be separated based on the event categories.

Could you please share the procedure if any?

**Comment by danielkrause** [comment]
Hey, yes, the audio data that was used for this generator is a curated version of FSD50K with a certain type of folder subdivision. I can send you.
The folder hierarchy goes roughly as follows:
dataset_dir -> class_name -> test/train -> sound_name -> *.wav

I can send you a version which is already processed to your e-mail if that's easier.

**Comment by sreenivasaupadhyaya** [comment]
> Hey, yes, the audio data that was used for this generator is a curated version of FSD50K with a certain type of folder subdivision. I can send you. The folder hierarchy goes roughly as follows: dataset_dir -> class_name -> test/train -> sound_name -> *.wav
> 
> I can send you a version which is already processed to your e-mail if that's easier.

Thank you for the information,
upadhyaya.sreenivasa@gmail.com
